apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'agenda-service'
spec:
  project: default
  source:
    repoURL: 'https://salaboy.github.io/helm/'
    targetRevision: v0.1.0
    chart: fmtok8s-agenda-service
  destination:
    namespace: conference
    name: dev
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true