apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'in-cluster'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/from-monolith-to-k8s'
    targetRevision: HEAD
    path: argocd/in-cluster
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}