apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
        - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
  template:
    metadata:
      name: 'cluster-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/morey-tech/from-monolith-to-k8s
        targetRevision: HEAD
        path: 'helm/cluster'
      destination:
        name: in-cluster
        namespace: 'argocd'
      syncPolicy:
        automated: {}
      #   syncOptions:
      #   - CreateNamespace=true