apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/morey-tech/from-monolith-to-k8s
      revision: HEAD
      directories:
      - path: argocd/*
      - path: argocd/staging*
        exclude: true
  template:
    metadata:
      name: 'cluster-{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/morey-tech/from-monolith-to-k8s
        targetRevision: HEAD
        path: 'helm/cluster'
      destination:
        name: in-cluster
        namespace: 'argocd'
      # syncPolicy:
      #   syncOptions:
      #   - CreateNamespace=true