apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'conference'
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/from-monolith-to-k8s'
    targetRevision: HEAD
    path: argocd/dev/conference
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true